version: "2"

services:
  reader:
    image: stiller/tweeteranalyzerdemo_reader:v1
    environment:
      - TwitterConsumerKey
      - TwitterConsumerSecret
      - TwitterAccessToken
      - TwitterAccessTokenSecret

  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports: 
     - "8080:15672"

  analyzer:
    image: stiller/tweeteranalyzerdemo_analyzer:v1
    environment:
      - TextAnalyticsApiKey

  aggregator:
    image: stiller/tweeteranalyzerdemo_aggregator:v2

  redis:
    image: redis:4.0.10-alpine

  result:
    image: stiller/tweeteranalyzerdemo_result:v2
    ports: 
      - "80:80"
